env:
  global:
  - REPO_DIR=.
  - BUILD_COMMIT=$TRAVIS_COMMIT
  - PLAT=x86_64
install:
  - "./build_wheel.sh"
script:
  - "./test_wheel.sh"
after_success:
 - "./deploy.sh"

matrix:
  include:
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.5

  - os: linux
    env:
    - MB_PYTHON_VERSION=3.6

  - os: linux
    env:
    - MB_PYTHON_VERSION=3.7

  - os: osx
    osx_image: xcode9.3
    env:
    - MB_PYTHON_VERSION=3.5

    # block deployment of source package - compiling from that would be an extra pain, better use github repo + tags
    # - DEPLOY_SDIST=true

  - os: osx
    osx_image: xcode9.3
    env:
    - MB_PYTHON_VERSION=3.6

  - os: osx
    osx_image: xcode9.3
    env:
    - MB_PYTHON_VERSION=3.7
